# Generated by Django 5.2.7 on 2025-10-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('length', models.IntegerField()),
                ('is_palindrome', models.BooleanField()),
                ('word_count', models.IntegerField()),
                ('sha256_hash', models.CharField(max_length=64, unique=True)),
                ('unique_characters', models.IntegerField()),
                ('char_frequency', models.JSONField()),
            ],
            options={
                'db_table': 'strings',
            },
        ),
    ]
