# Generated by Django 5.2.7 on 2025-10-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stringentry_delete_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(unique=True)),
                ('sha256_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('length', models.IntegerField()),
                ('is_palindrome', models.BooleanField(db_index=True)),
                ('unique_characters', models.IntegerField()),
                ('word_count', models.IntegerField(db_index=True)),
                ('character_frequency_map', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analyzed_strings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='StringEntry',
        ),
        migrations.AddIndex(
            model_name='analyzedstring',
            index=models.Index(fields=['sha256_hash'], name='analyzed_st_sha256__c2c118_idx'),
        ),
        migrations.AddIndex(
            model_name='analyzedstring',
            index=models.Index(fields=['is_palindrome'], name='analyzed_st_is_pali_4e89db_idx'),
        ),
        migrations.AddIndex(
            model_name='analyzedstring',
            index=models.Index(fields=['word_count'], name='analyzed_st_word_co_bf6cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='analyzedstring',
            index=models.Index(fields=['length'], name='analyzed_st_length_6b6fd7_idx'),
        ),
    ]
